import UI from "@products/Assets/UI.png";

export const productData = [
  {
    img: UI,
    title: "Learn Figma - UI/UX Design Essential Training",
    rating: 4.5,
    price: 100,
    creator: "Alex Lerans",
    date: "30/10/2024",
    verification: true,
  },
  {
    img: UI,
    title: "Learn Figma - UI/UX Design Essential Training",
    rating: 4.5,
    price: 100,
    creator: "Alex Lerans",
    date: "30/10/2024",
    verification: true,
  },
  {
    img: UI,
    title: "Learn Figma - UI/UX Design Essential Training",
    rating: 4.5,
    price: 100,
    creator: "Alex Lerans",
    date: "30/10/2024",
    verification: true,
  },
  {
    img: UI,
    title: "Learn Figma - UI/UX Design Essential Training",
    rating: 4.5,
    price: 100,
    creator: "Alex Lerans",
    date: "30/10/2024",
    verification: true,
  },
  {
    img: UI,
    title: "Learn Figma - UI/UX Design Essential Training",
    rating: 4.5,
    price: 100,
    creator: "Alex Lerans",
    date: "30/10/2024",
    verification: true,
  },
  {
    img: UI,
    title: "Learn Figma - UI/UX Design Essential Training",
    rating: 4.5,
    price: 100,
    creator: "Alex Lerans",
    date: "30/10/2024",
    verification: true,
  },
  {
    img: UI,
    title: "Learn Figma - UI/UX Design Essential Training",
    rating: 4.5,
    price: 100,
    creator: "Alex Lerans",
    date: "30/10/2024",
    verification: true,
  },
  {
    img: UI,
    title: "Learn Figma - UI/UX Design Essential Training",
    rating: 4.5,
    price: 100,
    creator: "Alex Lerans",
    date: "30/10/2024",
    verification: true,
  },
  {
    img: UI,
    title: "Learn Figma - UI/UX Design Essential Training",
    rating: 4.5,
    price: 100,
    creator: "Alex Lerans",
    date: "30/10/2024",
    verification: true,
  },
  {
    img: UI,
    title: "Learn Figma - UI/UX Design Essential Training",
    rating: 4.5,
    price: 100,
    creator: "Alex Lerans",
    date: "30/10/2024",
    verification: true,
  },
  {
    img: UI,
    title: "Learn Figma - UI/UX Design Essential Training",
    rating: 4.5,
    price: 100,
    creator: "Alex Lerans",
    date: "30/10/2024",
    verification: true,
  },
  {
    img: UI,
    title: "Learn Figma - UI/UX Design Essential Training",
    rating: 4.5,
    price: 100,
    creator: "Alex Lerans",
    date: "30/10/2024",
    verification: true,
  },
  {
    img: UI,
    title: "Learn Figma - UI/UX Design Essential Training",
    rating: 4.5,
    price: 100,
    creator: "Alex Lerans",
    date: "30/10/2024",
    verification: true,
  },
  {
    img: UI,
    title: "Learn Figma - UI/UX Design Essential Training",
    rating: 4.5,
    price: 100,
    creator: "Alex Lerans",
    date: "30/10/2024",
    verification: true,
  },
  {
    img: UI,
    title: "Learn Figma - UI/UX Design Essential Training",
    rating: 4.5,
    price: 100,
    creator: "Alex Lerans",
    date: "30/10/2024",
    verification: true,
  },
  {
    img: UI,
    title: "Learn Figma - UI/UX Design Essential Training",
    rating: 4.5,
    price: 100,
    creator: "Alex Lerans",
    date: "30/10/2024",
    verification: false,
  },
  {
    img: UI,
    title: "Learn Figma - UI/UX Design Essential Training",
    rating: 4.5,
    price: 100,
    creator: "Alex Lerans",
    date: "30/10/2024",
    verification: false,
  },
  {
    img: UI,
    title: "Learn Figma - UI/UX Design Essential Training",
    rating: 4.5,
    price: 100,
    creator: "Alex Lerans",
    date: "30/10/2024",
    verification: false,
  },
  {
    img: UI,
    title: "Learn Figma - UI/UX Design Essential Training",
    rating: 4.5,
    price: 100,
    creator: "Alex Lerans",
    date: "30/10/2024",
    verification: true,
  },
  {
    img: UI,
    title: "Learn Figma - UI/UX Design Essential Training",
    rating: 4.5,
    price: 100,
    creator: "Alex Lerans",
    date: "30/10/2024",
    verification: true,
  },
  {
    img: UI,
    title: "Learn Figma - UI/UX Design Essential Training",
    rating: 4.5,
    price: 100,
    creator: "Alex Lerans",
    date: "30/10/2024",
    verification: false,
  },
  {
    img: UI,
    title: "Learn Figma - UI/UX Design Essential Training",
    rating: 4.5,
    price: 100,
    creator: "Alex Lerans",
    date: "30/10/2024",
    verification: true,
  },
];
